services:
  php83:
    image: alexeyp0708/dev-php83-alpine
    container_name: php83
    restart: always
    healthcheck:
      test: ["CMD","/docker_scripts/healthcheck/test.sh","php-fpm","9000"]
      interval: 10m
      start_interval: 3s
      start_period: 1m
#    depends_on:
#      mysql:
#        restart: true
#        condition: service_healthy
    environment:
      HOSTNAME: php83
    networks: 
      default:
#      vlan_network: 
#        ipv4_address: ${PHP83_IPV4}
    volumes:
      - dev:/mnt/data
networks:
  default:
    driver: bridge
    vlan_network:
    name: "${NETWORK_ID}"
    external: true
volumes:
  dev:
    external: true
    name: webserver-data