services:
  ftp:
    image: alexeyp0708/dev-vsftpd:latest
    container_name: ftp
    restart: always
    depends_on:
      nginx:
        restart: true
        condition: service_healthy
    environment:
      HOSTNAME: FTP  
      USERS_LIST: >
        www-data "www-data" /mnt/data www-data
      VSFTPD_CONFIG: >
        background=YES\n
        local_root=/mnt/data/FTP/$$USER\n
        guest_enable=YES\n
        pam_service_name=vsftpd_virtual\n
        virtual_use_local_privs=YES
    command: -c /etc/vsftpd/collection/basic.conf
    volumes:
      - dev:/mnt/data
    networks:
      vlan_network: 
        ipv4_address: ${FTP_IPV4}
networks:
  default:
    driver: bridge
  vlan_network:
    name: "${NETWORK_ID}"
    external: true
volumes:
  dev:
    external: true
    name: webserver-data