services:
#  nginx:
#    image: alexeyp0708/dev-nginx-alpine
#    container_name: nginx
#    restart: always
#    healthcheck:
#      test: ["CMD","/docker_scripts/healthcheck/test.sh"]
#      interval: 10m
#      start_interval: 3s
#      start_period: 1m
#    environment:
#        HOSTNAME: nginx
#    networks: 
#      default:
#      vlan_network: 
#        ipv4_address: ${NGINX_IPV4}
#    volumes:
#      - dev:/mnt/data
  nodejs:
    build: ../../images/dev-nodejs-alpine
    container_name: nodejs
    stdin_open: true
    tty: true
    #restart: always
    #healthcheck:
    #  test: ["CMD","/docker_scripts/healthcheck/test.sh","php-fpm","9000"]
    #  interval: 10m
    #  start_interval: 3s
    #  start_period: 1m
    #depends_on:
    #  mysql:
    #    restart: true
    #    condition: service_healthy
    environment:
      HOSTNAME: nodejs
    networks:
      default:
      vlan_network: 
        ipv4_address: ${NODEJS_IPV4}
    volumes:
      - dev:/mnt/data
networks:
  default:
    driver: bridge
  vlan_network:
    name: "${NETWORK_ID}"
    external: true
volumes:
  dev: